### PR TITLE
Cross-compilation for 2.12.0-M2

### PR DESCRIPTION
**Pull request by holograph**
Tested locally with [Accord](https://github.com/wix/accord/tree/scala-2.12). Fixes issue #1.

### CODE REVIEW

**Comment by xeno-by** [comment]
Thanks! Released: https://oss.sonatype.org/content/repositories/releases/org/scalamacros/resetallattrs_2.12.0-M2/

**Comment by holograph** [comment]
@xeno-by Hey, that's a 1.0.0 release -- any reason there isn't one for 2.11? (the only one appears to be 1.0.0-M1).

**Comment by xeno-by** [comment]
Good point. Released 1.0.0 for 2.11 :)

**Comment by holograph** [comment]
Thanks, updated :-)

**Pull request merged**
